# Define imagem base
FROM python:3.10-slim 

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia um arquivo para o diretório de trabalho no container
COPY main.py .

# Define o comando a ser executado quando o container iniciar
CMD ["python", "main.py"]